
# Info
title: Pega Labs Note
twitter: "https://twitter.com/pegalabs"
github: "https://github.com/pegalabs"
baseurl: "https://pegalabs.github.io/labs"
url: "https://pegalabs.github.io/"

# Collections
collections:
  posts:
    title: Posts
    output: true
    permalink: "/news/:title"

# Settings
markdown: kramdown
gems:
excerpt_seperator: "<!--more-->"
destination: "./build"
permalink: "/:titsle"
exclude:
  - components
  - Gemfile
  - Gemfile.lock
  - ".gitignore"
  - node_modules
  - js/source.js
  - webpack.config.js
  - package.json
  - .jshintrc
  - .sass-cache
  - browser-sync.js
  - npm-debug.log
  - README.MD
sass:
  style: compressed
